imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: elasticsearch.yml }
    - { resource: vrijwilligers_params.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: nl

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    default_locale:  "%locale%"
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ["twig"]
        #assets_version: SomeVersionScheme
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        fb_id: "%fb_id%"
        linkedin_id: "%linkedin_id%"
        googlemaps_key: "%googlemaps_key%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# OAUTH
hwi_oauth:
    firewall_names: [main]
    resource_owners:
        google:
            type:                google
            client_id:        "744185804186-i597ufhjha9rvqdrhquhao4bil9e58n2.apps.googleusercontent.com"
            client_secret:     "pDI2htdWTSloNKD5be-RWJBd"
            scope:               "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"


services:
    # Injectors
    ElasticsearchQuery:
        class: AppBundle\Elasticsearch\ElasticsearchQuery
        calls:
            - [setIndex, ["%elasticsearch_index%"]]
            - [setHost, ["%elasticsearch_host%"]]
            - [setPort, ["%elasticsearch_port%"]]
            - [create]

    UrlEncoder:
        class: AppBundle\UrlEncoder\UrlEncoder
        calls:
            - [setEm, ["@doctrine.orm.entity_manager"]]
    # Services
    url.listener:
        class: AppBundle\EventListener\UrlListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
