fos_elastica:
    clients:
        default: { host: "%elasticsearch_host%", port: "%elasticsearch_port%" }
    indexes:
        %elasticsearch_index%:
            finder: ~
            settings:
                index:
                    analysis:
                        analyzer:
                            nl_analyzer:
                                type: snowball
                                language: Dutch
                            # other analyzers
            types:
                person:
                    mappings:
                        id: "%nl%"
                        firstName: "%nl%"
                        lastName: "%nl%"
                        username: "%nl%"
                        email: "%nl%"
                        street: "%nl%"
                        number: "%nl%"
                        bus: "%nl%"
                        postalcode: "%nl%"
                        city: "%nl%"
                        telephone: "%nl%"
                        language: "%nl%"
                        linkedinUrl: "%nl%"
                        isActive: "%nl%"
                        contactOrganisation: "%nl%"
                        # organisation: "%nl%"
                        # testimonials: "%nl%"
                        # skills: "%nl%"
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Person
                        provider: ~
                        listener: %listener%
                        finder: ~
                        elastica_to_model_transformer:
                            ignore_missing: true
                organisation:
                    mappings:
                        id: "%nl%"
                        name: "%nl%"
                        type: "%nl%"
                        intermediary: "%nl%"
                        description: "%nl%"
                        creator: "%nl%"
                        email: "%nl%"
                        street: "%nl%"
                        number: "%nl%"
                        postalcode: "%nl%"
                        bus: "%nl%"
                        city: "%nl%"
                        urlId: "%nl%"
                        slogans: "%nl%"
                        telephone: "%nl%"
                        website: "%nl%"
                        # creator: "%nl%"
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Organisation
                        provider: ~
                        listener: %listener%
                        finder: ~
                        elastica_to_model_transformer:
                            ignore_missing: true
                # skill:
                #     mappings:
                #         name: %nl%
                #     persistence:
                #         driver: orm
                #         model: AppBundle\Entity\Skill
                #         provider: ~
                #         listener: %listener%
                #         finder: ~
                #         elastica_to_model_transformer:
                #             ignore_missing: true

                # testimonial:
                #     mappings:
                #         value: %nl%
                #         sender: %nl%
                #         receiver: %nl%
                #     persistence:
                #         driver: orm
                #         model: AppBundle\Entity\Testimonial
                #         provider: ~
                #         listener: %listener%
                #         finder: ~
                #         elastica_to_model_transformer:
                #             ignore_missing: true

                vacancy:
                    mappings:
                        id: "%nl%"
                        title: "%nl%"
                        description: "%nl%"
                        startdate: "%nl%"
                        enddate: "%nl%"
                        urlId: "%nl%"
                        organisation: "%nl%"
                        summary: "%nl%"
                        longterm: "%nl%"
                        street: "%nl%"
                        number: "%nl%"
                        postalcode: "%nl%"
                        bus: "%nl%"
                        city: "%nl%"
                        estimatedWorkInHours: "%nl%"
                        socialInteraction: "%nl%"
                        independent: "%nl%"
                        renumeration: "%nl%"
                        otherReward: "%nl%"
                        published: "%nl%"
                        wanted: "%nl%"
                        stillWanted: "%nl%"
                        # skills: "%nl%"
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Vacancy
                        provider: ~
                        listener: %listener%
                        finder: ~
                        elastica_to_model_transformer:
                            ignore_missing: true
