hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login
 
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
 
google_login:
    path: /login/google

app:
    resource: "@AppBundle/Controller/"
    type:     annotation 
logout:
    path: /logout
