# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\Person:
            algorithm: bcrypt
            cost: 15

    # http://symfony.com/doc/current/security/multiple_user_providers.html
    providers:
        chain_provider:
            chain:
                providers: [user_name_provider, user_mail_provider, user_tel_provider]
        user_name_provider:
            entity:
                class: AppBundle:Person
                property: username
        user_mail_provider:
            entity:
                class: AppBundle:Person
                property: email
        user_tel_provider:
            entity:
                class: AppBundle:Person
                property: telephone
                # if you're using multiple entity managers
                # manager_name: customer

        # in_memory:
        #     memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            methods: [GET, POST]
            # provider: user_db_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /persoon
            logout:
                path:   /logout
                target: /

        main:
            pattern:    ^/
            # provider: user_db_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /persoon
            logout:
                path:   /logout
                target: /
            oauth:
                resource_owners:
                    google: "/login/check-google"
                    facebook: "/login/check-facebook"
                login_path: login
                failure_path: login
                oauth_user_provider:
                    service: ib_user.oauth_user_provider
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

          # uncomment to enable https on /login
    access_control:
        # - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        # - { path: /nieuw, roles: ROLE_USER }

    role_hierarchy:
        ROLE_VOLUNTEER:   ROLE_USER
        ROLE_ORGANISATION: [ROLE_USER, ROLE_VOLUNTEER]
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
