# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    hwi_oauth.user.provider.entity:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider
    ib_user.oauth_user_provider:
        class: AppBundle\Auth\OAuthProvider
        arguments: ["@session", "@doctrine", "@service_container"]
    random:
        class: AppBundle\Utils\Random
    doctrineUtils:
        class: AppBundle\Utils\DoctrineUtils
    # doctrine.orm.validator.unique:
    #     class: Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntityValidator
    #     arguments:
    #         - "@doctrine.orm.entity_manager"
    #     tags:
    #         - { name: validator.constraint_validator }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
