parameters:
    elasticsearch_host: localhost
    elasticsearch_port: 9200
    elasticsearch_index: homestead

    nl: {analyzer: nl_analyzer}
    listener:
        insert: true
        update: true
        delete: true
        logger: true
        # immediate: true

    fb_id: '990174991070590'
    linkedin_id: '77lr8oxzq2u5j9'

