AppBundle\Entity\Candidacy:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        state:
            type: smallint
            nullable: true
    manyToOne:
        person:
            targetEntity: Person
            inversedBy: candidacies
            joinColumn:
                name: person
                referencedColumnName: id
        vacancy:
            targetEntity: Vacancy
            inversedBy: candidacies
            joinColumn:
                name: vacancy
                referencedColumnName: id  