AppBundle\Entity\Contact:
    type: entity
    table: Contact
    uniqueConstraints:
        Id:
            columns:
                - Id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: Id
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: Email
        address:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: Address
        telephone:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            column: Telephone
    lifecycleCallbacks: {  }
