AppBundle\Entity\Organisation:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 150
        intermediary:
            type: boolean
            options: {default: false}
        type:
            type: string
            length: 3
        description:
            type: text
        email:
            type: string
            length: 255
            nullable: true
        street:
            type: string
            scale: 255
            nullable: true
        number:
            type: smallint
            nullable: true
        postalCode:
            type: smallint
            nullable: true
        bus:
            type: string
            length: 6
            nullable: true
        city:
            type: string
            scale: 100
            nullable: true
        telephone:
            type: string
            length: 35
            nullable: true
        description:
            type: text
        urlid:
            type: string
            length: 150
            options: {default: ""}
        logoName:
            type: string
            length: 255
            nullable: true
        slogan:
            type: string
            length: 255
            nullable: true
        website:
            type: string
            length: 150
            nullable: true
    manyToOne:
        creator:
            targetEntity: Person
            inversedBy: organisation
            joinColumn:
                name: creator_id
                referencedColumnName: id
    manyToMany:
        administrators:
          targetEntity: Person
          mappedBy: organisations
        likers:
          targetEntity: Person
          mappedBy: liked_organisations
          cascade: ["persist"]
    oneToMany:
        vacancies:
            nullable: true
            targetEntity: Vacancy
            mappedBy: organisation