AppBundle\Entity\Organisation:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 150
        intermediary:
            type: boolean
        deleted:
            type: boolean
        type:
            type: string
            length: 3
            nullable: true
        description:
            type: text
        email:
            type: string
            length: 255
            nullable: true
        street:
            type: string
            scale: 255
            nullable: true
        number:
            type: smallint
            nullable: true
        postalCode:
            type: smallint
            nullable: true
        bus:
            type: string
            length: 6
            nullable: true
        city:
            type: string
            scale: 100
            nullable: true
        latitude:
            type: string
            nullable: true
        longitude:
            type: string
            nullable: true
        telephone:
            type: string
            length: 35
            nullable: true
        description:
            type: text
        urlid:
            type: string
            length: 150
            options: {default: ""}
        logoName:
            type: string
            length: 255
            nullable: true
        slogan:
            type: string
            length: 255
            nullable: true
        website:
            type: string
            length: 150
            nullable: true
    manyToOne:
        creator:
            targetEntity: Person
            inversedBy: organisation
            joinColumn:
                name: creator_id
                referencedColumnName: id
    manyToMany:
        administrators:
          targetEntity: Person
          orderBy: { 'digest': 'ASC' }
          mappedBy: organisations
        alerts:
          targetEntity: Person
          mappedBy: organisation_alerts
        likers:
          targetEntity: Person
          mappedBy: liked_organisations
          cascade: ["persist"]
        sectors:
            targetEntity: Skill
            mappedBy: null
            cascade: ["persist"]
            nullable: true
            joinTable:
                name: sector_for_organisation
                joinColumns:
                    -
                        name: organisation_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: skill_id
                        referencedColumnName: id
    oneToMany:
        vacancies:
            nullable: true
            targetEntity: Vacancy
            mappedBy: organisation