AppBundle\Entity\Organisation:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 150
        email:
            type: string
            length: 255
        street:
            type: string
            scale: 255
        number:
            type: smallint
        postalCode:
            type: smallint
        bus:
            type: smallint
            nullable: true
        city:
            type: string
            scale: 100
        telephone:
            type: string
            length: 10
        description:
            type: text
    oneToOne:
        creator:
            targetEntity: Person
            inversedBy: organisation
            joinColumn:
                name: creator_id
                referencedColumnName: id
    oneToMany:
        vacancies:
            targetEntity: Vacancy
            mappedBy: organisation
