AppBundle\Entity\PasswordRecover:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        hash:
            type: string
            length: 300
        expiryDate:
            type: string
            length: 150
    oneToOne:
        person:
          targetEntity: AppBundle\Entity\Person
          joinColumn:
            name: person_id
            referencedColumnName: id