AppBundle\Entity\Person:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        firstname:
            type: string
            length: 100
        lastname:
            type: string
            length: 100
        username:
            type: string
            length: 150
        passphrase:
            type: string
            length: 60
        street:
            type: string
            scale: 255
        number:
            type: smallint
        postalcode:
            type: smallint
        bus:
            type: smallint
            nullable: true
        city:
            type: string
            scale: 100
        email:
            type: string
            length: 255
        telephone:
            type: string
            length: 10
            nullable: true
        linkedinUrl:
            type: string
            length: 150
            nullable: true
    OneToOne:
            targetEntity: Organisation
            mappedBy: id
    OneToMany:
        testimonials:
            targetEntity: Testimonial
            mappedBy: id
    manyToMany:
        skills:
            targetEntity: Skill
            mappedBy: null
            joinTable:
                name: person_has_skill
                joinColumns:
                    -
                        name: person_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: skill_id
                        referencedColumnName: id
