AppBundle\Entity\Person:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        firstname:
            type: string
            length: 100
        lastname:
            type: string
            length: 100
        username:
            type: string
            length: 150
            nullable: true
        passphrase:
            type: string
            length: 60
        street:
            type: string
            scale: 255
            nullable: true
        number:
            type: smallint
            nullable: true
        postalcode:
            type: smallint
            nullable: true
        bus:
            type: string
            length: 6
            nullable: true
        city:
            type: string
            scale: 100
            nullable: true
        latitude:
            type: string
            nullable: true
        longitude:
            type: string
            nullable: true
        email:
            type: string
            length: 255
            nullable: true
        telephone:
            type: string
            length: 35
            nullable: true
        language:
            type: string
            length: 2
            nullable: false
            options:
                default: nl
        linkedinUrl:
            type: string
            length: 150
            nullable: true
        avatarName:
            type: string
            length: 255
            nullable: true
        digest:
            type: smallint
            options: { default: 1 }
        access:
            type: boolean
            options: { default: false }
        renumerate:
            type: boolean
            options: { default: true }
        longterm:
            type: boolean
            options: { default: true }
        estimatedWorkInHours:
            type: smallint
            nullable: true
            options: { default: 0 }
        socialInteraction:
            type: string
            length: 10
            options: { default: "normal" }
        superadmin:
            type: boolean
            options: { default: false }
        alertPersonal:
            type: smallint
            nullable: true
            options: { default: 1 }
        alertOrganisations:
            type: smallint
            nullable: true
            options: { default: 1 }
        alertVacancies:
            type: smallint
            nullable: true
            options: { default: 1 }
    oneToMany:
        organisation:
            targetEntity: Organisation
            mappedBy: creator
        candidacies:
            targetEntity: Candidacy
            mappedBy: candidate
        alertsettings:
            targetEntity: AlertSetting
            mappedBy: person_id
        vacancies:
            targetEntity: Vacancy
            mappedBy: creator

    manyToOne:
        contactOrganisation:
            targetEntity: Organisation
            joinColumn:
                name: contactOrganisation_id
                referencedColumnName: id
    manyToMany:
        skills:
            targetEntity: Skill
            mappedBy: null
            cascade: ["persist"]
            nullable: true
            joinTable:
                name: person_has_skill
                joinColumns:
                    -
                        name: person_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: skill_id
                        referencedColumnName: id
        organisations:
          targetEntity: Organisation
          inversedBy: administrators
          joinTable:
            name: organisations_administrators
            joinColumns:
              person_id:
                referencedColumnName: id
            inverseJoinColumns:
              organisation_id:
                referencedColumnName: id
        liked_organisations:
          targetEntity: Organisation
          inversedBy: likers
          cascade: ["persist"]
          joinTable:
            name: organisations_likers
            joinColumns:
              person_id:
                referencedColumnName: id
            inverseJoinColumns:
              organisation_id:
                referencedColumnName: id
        liked_vacancies:
          targetEntity: Vacancy
          inversedBy: likers
          cascade: ["persist"]
          joinTable:
            name: vacancies_likers
            joinColumns:
              person_id:
                referencedColumnName: id
            inverseJoinColumns:
              vacancy_id:
                referencedColumnName: id