AppBundle\Entity\Skill:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
            unique: true
    manyToOne:
        parent:
            nullable: true
            targetEntity: Skill
            joinColumn:
                name: parent_id
                referencedColumnName: id
    manyToMany:
        vacancies:
            targetEntity: Vacancy
            mappedBy: skills
