AppBundle\Entity\Skill:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
    manyToOne:
        parent:
            nullable: true
            targetEntity: Skill
            joinColumn:
                name: parent_id
                referencedColumnName: id
    ManyToMany:
        vacancies:
            targetEntity: Vacancy
            joinTable:
                name: vacancy_has_skills
                joinColumns:
                    skill_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    vacancy_id:
                        referencedColumnName: id
