AppBundle\Entity\Skillproficiency:
    type: entity
    table: SkillProficiency
    indexes:
        FKSkillProfi479319:
            columns:
                - Type
    uniqueConstraints:
        Id:
            columns:
                - Id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: Id
            generator:
                strategy: IDENTITY
    fields:
        proficiency:
            type: boolean
            nullable: false
            column: Proficiency
    manyToOne:
        type:
            targetEntity: Skill
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                Type:
                    referencedColumnName: Id
            orphanRemoval: false
    lifecycleCallbacks: {  }
