AppBundle\Entity\Testimonial:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        value:
            type: text
        approved:
            type: boolean
            nullable: true
    manyToOne:
        sender:
            targetEntity: Person
            joinColumn:
                name: sender_id
                referencedColumnName: id
        senderVacancy:
            targetEntity: Vacancy
            joinColumn:
                name: sender_vacancy_id
                referencedColumnName: id
        receiverVacancy:
            targetEntity: Vacancy
            joinColumn:
                name: receiver_vacancy_id
                referencedColumnName: id
        receiverPerson:
            targetEntity: Person
            joinColumn:
                name: receiver_person_id
                referencedColumnName: id

