AppBundle\Entity\Testanswer:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        answer:
            type: string
            length: 200
        weight:
            type: smallint
            nullable: true
        skill:
            type: integer
            nullable: true
        type1score:
            type: integer
            nullable: true
        type2score:
            type: integer
            nullable: true
        type3score:
            type: integer
            nullable: true
        type4score:
            type: integer
            nullable: true
        type5score:
            type: integer
            nullable: true
    manyToOne:
        question:
            targetEntity: Testquestion
            mappedBy: id