AppBundle\Entity\Testimonial:
    type: entity
    table: Testimonial
    indexes:
        FKTestimonia20655:
            columns:
                - SenderId
        FKTestimonia893114:
            columns:
                - ReceiverId
    uniqueConstraints:
        Id:
            columns:
                - Id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: Id
            generator:
                strategy: IDENTITY
    fields:
        value:
            type: string
            nullable: false
            length: 2000
            options:
                fixed: false
            column: Value
    manyToOne:
        senderid:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                SenderId:
                    referencedColumnName: Id
            orphanRemoval: false
        receiverid:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ReceiverId:
                    referencedColumnName: Id
            orphanRemoval: false
    lifecycleCallbacks: {  }
