AppBundle\Entity\Testimonial:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        value:
            type: text
        approved:
            type: boolean
    manyToOne:
        sender:
            targetEntity: Person
            inversedBy: Testimonials
            joinColumn:
                name: sender_id
                referencedColumnName: id
        receiver:
            targetEntity: Person
            inversedBy: Testimonials
            joinColumn:
                name: receiver_id
                referencedColumnName: id
