AppBundle\Entity\Vacancy:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 100
        description:
            type: text
        startdate:
            type: datetime
        enddate:
            type: datetime
    manyToOne:
        organisation:
            targetEntity: Organisation
            inversedBy: Organisations
            joinColumn:
                name: organisation_id
                referencedColumnName: id
    ManyToMany:
        skills:
            targetEntity: Skill
            joinTable:
                name: vacancy_has_skills
                joinColumns:
                    vacancy_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    skill_id:
                        referencedColumnName: id
