AppBundle\Entity\Vacancyskill:
    type: entity
    table: VacancySkill
    indexes:
        FKVacancySki10694:
            columns:
                - ProficiencyId
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: Id
    oneToOne:
        proficiencyid:
            targetEntity: Skillproficiency
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ProficiencyId:
                    referencedColumnName: Id
            orphanRemoval: false
    lifecycleCallbacks: {  }
