AppBundle\Entity\Vacancy:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 100
        description:
            type: text
        startdate:
            type: datetime
        enddate:
            type: datetime
    manyToOne:
        organisation:
            targetEntity: Organisation
            inversedBy: Organisations
            joinColumn:
                name: organisation_id
                referencedColumnName: id
    manyToMany:
        skills:
            targetEntity: Skill
            mappedBy: null
            inversedBy: vacancy
            joinTable:
                name: vacancy_has_skill
                joinColumns:
                    -
                        name: vacancy_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: skill_id
                        referencedColumnName: id
