AppBundle\Entity\Vacancy:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 100
        summary:
            type: string
            length: 120
            nullable: true
        description:
            type: text
        longterm:
            type: boolean
            options: {default: false}
        estimatedWorkInHours:
            type: smallint
            nullable: true
        street:
            type: string
            scale: 255
            nullable: true
        number:
            type: smallint
            nullable: true
        postalCode:
            type: smallint
            nullable: true
        bus:
            type: string
            length: 6
            nullable: true
        city:
            type: string
            scale: 100
            nullable: true
        latitude:
            type: string
            nullable: true
        longitude:
            type: string
            nullable: true
        access:
            type: boolean
            options: {default: false}
        socialInteraction:
            type: string
            length: 10
            options: { default: "normal" }
        independent:
            type: string
            length: 11
            nullable: true
        startdate:
            type: date
        enddate:
            type: date
            nullable: true
        renumeration:
            type: decimal
            nullable: true
        otherReward:
            type: string
            length: 200
            nullable: true
        published:
            type: smallint
            options: { default: 1 }
        wanted:
            type: smallint
            options: { default: 1 }
        stillWanted:
            type: smallint
            options: { default: 1 }
        urlid:
            type: string
            length: 100
            options: {default: ""}
    manyToOne:
        organisation:
            targetEntity: Organisation
            inversedBy: vacancies
            joinColumn:
                name: organisation_id
                referencedColumnName: id
        creator:
             targetEntity: Person
             inversedBy: vacancies
             joinColumn:
                name: creator_id
                referencedColumnName: id

    oneToMany:
        candidacies:
            targetEntity: Candidacy
            mappedBy: vacancy
    manyToMany:
        skills:
            targetEntity: Skill
            nullable: true
            mappedBy: null
            inversedBy: vacancies
            cascade: ["persist"]
            joinTable:
                name: vacancy_has_skill
                joinColumns:
                    -
                        name: vacancy_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: skill_id
                        referencedColumnName: id
        likers:
          targetEntity: Person
          mappedBy: liked_vacancies
          cascade: ["persist"]
