AppBundle\Entity\Vacancy:
    type: entity
    table: Vacancy
    indexes:
        FKVacancy396991:
            columns:
                - OrganisationId
    uniqueConstraints:
        Id:
            columns:
                - Id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: Id
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
            column: Title
        description:
            type: string
            nullable: false
            length: 2000
            options:
                fixed: false
            column: Description
        startdate:
            type: datetime
            nullable: true
            column: StartDate
        enddate:
            type: datetime
            nullable: true
            column: EndDate
        creationtime:
            type: datetime
            nullable: true
            column: CreationTime
        skillid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: SkillId
    manyToOne:
        organisationid:
            targetEntity: Organisation
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                OrganisationId:
                    referencedColumnName: Id
            orphanRemoval: false
    lifecycleCallbacks: {  }
